### ISSUE TITLE
Drop down menu

### ISSUE THREAD

**Issue by kobeumut** [kobeumut/MegaMenu#1]
Add vue-triggered drop-down menu.

**Comment by albin-jose** [comment]
Hi @kobeumut can i work on this issue

**Comment by kobeumut** [comment]
@albin-jose sure I'l waiting for your pr :)

**Comment by albin-jose** [comment]
Thanks @kobeumut

**Comment by kobeumut** [comment]
@albin-jose thanks for dropdown
#4
