### ISSUE TITLE
Tabs Menu

### ISSUE THREAD

**Issue by kobeumut** [kobeumut/MegaMenu#5]
![feature](https://user-images.githubusercontent.com/5182289/66257513-d96c9180-e7a2-11e9-9da8-2e8e5a22df13.gif)

Menu block sample that can be changed by clicking on the tabs will be added

https://app.leanboard.io/board/2231a89e-8085-40e4-8926-7680161b20fb

**Comment by albin-jose** [comment]
Hi @kobeumut can i work on this issue

**Comment by albin-jose** [comment]
@kobeumut should i place the tabs at the top or bottom

**Comment by kobeumut** [comment]
#6  thanks @albin-jose
